version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME:-yatv}
      - MYSQL_USER=${DB_USER:-yatv_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-yatv_pass}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_pass}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
